# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails # 追加

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

Layout/TrailingWhitespace:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Style/BlockDelimiters:
  Exclude:
    - "spec/**/*"

# 追加の設定
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 2

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 2

# 追加の緩和ルール
Rails/I18nLocaleTexts:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Layout/MultilineOperationIndentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
