plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Enabled: true
  Max: 40 # 25から40に増加
  Exclude:
    - "spec/**/*_spec.rb"
    - "config/routes.rb"
    - "config/environments/*.rb"

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - "spec/**/*_spec.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument
  Exclude:
    - "spec/**/*_spec.rb"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

# メトリクス関連の設定を緩和
Metrics/AbcSize:
  Max: 50 # 25から50に増加

Metrics/MethodLength:
  Max: 40 # 20から40に増加

# トランザクション内のreturnステートメントに対する警告を無視
Rails/TransactionExitStatement:
  Enabled: false

# ローカライゼーション関連
Rails/I18nLocaleTexts:
  Enabled: false # 今回はオフにする

# RSpecの設定
RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 10

RSpec/NestedGroups:
  Max: 5

# コンテキスト名の検証を無効化
RSpec/ContextWording:
  Enabled: false

# described_classの使用を無効化
RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5 # 3から5に増加

RSpec/ExampleLength:
  Max: 10

# シングルクォートを強制
Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/InstanceVariable:
  Enabled: true
  Exclude:
    - "spec/controllers/**/*_spec.rb"

RSpecRails/InferredSpecType:
  Enabled: false

# HashAlignmentを無効化
Layout/HashAlignment:
  Enabled: false

# ハッシュのインデントを無効化
Layout/FirstHashElementIndentation:
  Enabled: false

# 単一行のif文のスタイル警告を無効化
Style/IfUnlessModifier:
  Enabled: false

# マイグレーションファイルの警告を抑制
Style/Documentation:
  Exclude:
    - "db/migrate/**/*.rb"

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/**/*.rb"

Style/SymbolArray:
  Exclude:
    - "db/migrate/**/*.rb"

# Time.nowの警告を抑制
Rails/TimeZone:
  Enabled: false

# RSpecのメタデータスタイルの警告を抑制
RSpec/MetadataStyle:
  Enabled: false
