services: # コンテナの定義開始
  db: # PostgreSQLデータベースの設定
    image: postgres # 「Docker で PostgreSQL を動かすよ！」という設定。Docker Hub からイメージを取得
    restart: always # コンテナを常に再起動
    env_file: .env # 環境変数を .env から読み込む
    environment: # 環境変数の設定
      TZ: Asia/Tokyo # タイムゾーンを日本に設定
    volumes: # データの永続化設定
      - postgresql_data:/var/lib/postgresql/data # DBデータを永続化　postgresql_data にDBデータを保存して、コンテナを削除してもデータが消えないようにしている！
    ports: # ポート設定
       - "${POSTGRES_PORT}:5432" # .env でポートを設定 # ホストPC（ローカル環境）の5432番ポート と コンテナの5432番ポート を接続。
    healthcheck: # コンテナの健康チェック設定
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"] # PostgreSQLに接続できるか確認
      interval: 10s # チェック間隔
      timeout: 5s # タイムアウト時間
      retries: 5 # リトライ回数

  web: # Railsアプリケーションの設定
    build: # Dockerイメージのビルド設定
      context: . # ビルドコンテキストはカレントディレクトリ
      dockerfile: Dockerfile.dev # 開発用Dockerfileを使用
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    # ↑ サーバー起動時のコマンド：
    # - bundle install: 必要なgemをインストール
    # - rails db:prepare: DBの準備（migrate & create）
    # - サーバープロセスIDファイルの削除
    # - 開発サーバーの起動

    tty: true # 疑似ターミナルを割り当て
    stdin_open: true # 標準入力を保持
    env_file: .env # 環境変数を .env から読み込む
    volumes: # ボリュームマウントの設定
      - .:/app # Rails のソースコードをコンテナと同期
      - bundle_data:/usr/local/bundle:cached # Gem のインストールを永続化
      - node_modules:/app/node_modules # Node.js の node_modules を永続化
    ports: # ポート設定
      - "3000:3000" # Rails標準のポート
    # ↓ DBが「準備OK」になるまで Rails を起動しない！
    depends_on: # 依存関係の設定
      db: # dbサービスに依存
        condition: service_healthy # dbの健康チェックが通るまで待機

volumes: # ボリュームの定義
  bundle_data: # gemデータの永続化用ボリューム
  postgresql_data: # PostgreSQLデータの永続化用ボリューム
  node_modules: # Node.jsパッケージの永続化用ボリューム
