# Rubyのバージョンを指定した公式イメージをベースに使用
FROM ruby:3.3.6

# 必要なパッケージのインストール
RUN apt-get update -qq \
 && apt-get install -y nodejs postgresql-client npm vim \
 && rm -rf /var/lib/apt/lists/* \
 && npm install --global yarn

# 既存のbundlerをアンインストールし、特定のバージョンをインストール
RUN gem uninstall bundler -a -x \
    && gem install bundler -v 2.6.3

# GemのインストールパスとRubyGemsの設定を追加
ENV BUNDLE_PATH=/myapp/vendor/bundle
ENV GEM_HOME=/usr/local/bundle
ENV PATH $GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH

# コンテナの作業ディレクトリを指定
RUN mkdir /myapp
WORKDIR /myapp

# bundlerの設定を明示的に行う
RUN bundle config set path '/myapp/vendor/bundle'

# ホストのGemfileとGemfile.lockをコンテナにコピー
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

# 特定のバージョンでbundle installを実行
RUN bundle _2.6.3_ install

# カレントディレクトリのファイルをコンテナにコピー
ADD . /myapp

# コンテナ起動時に実行されるスクリプトをコピーして実行可能にする
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

# コンテナが外部に公開するポート番号を指定
EXPOSE 3000

# コンテナ起動時に実行されるメインプロセスを指定
CMD ["rails", "server", "-b", "0.0.0.0"]
