# 開発環境用

# Ruby のベースイメージを指定
FROM ruby:3.3.6

# 環境変数の設定
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要なパッケージのインストール（本当に必要なものだけ）
RUN apt-get update -qq && apt-get install -y \
  # Cコンパイラやツールを入れる（Gem のインストールに必須）
  build-essential \
  # PostgreSQL を使うために必須（Rails の pg gem が依存）
  libpq-dev \
  # JavaScript を実行する環境
  nodejs \
  # フロントエンドのパッケージ管理に必要
  yarn

# アプリケーションディレクトリの作成
RUN mkdir /app
WORKDIR /app

# Bundlerのインストール
RUN gem install bundler

# アプリケーションのコードをコピー
COPY . /app
