services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bin/dev"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      RAILS_ENV: development
      BUNDLE_PATH: /myapp/vendor/bundle
      GEM_HOME: /usr/local/bundle
    volumes:
      - .:/myapp
      - bundle_data:/myapp/vendor/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis

  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   command: bash -c "bundle install && bundle exec rails db:test:prepare && bundle exec rspec"
  #   env_file:
  #     - .env
  #   environment:
  #     RAILS_MASTER_KEY: ${TEST_RAILS_MASTER_KEY} # test.keyの内容を使用
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_HOST: db
  #     REDIS_URL: ${REDIS_URL}
  #     RAILS_ENV: test
  #     BUNDLE_PATH: /myapp/vendor/bundle
  #     GEM_HOME: /usr/local/bundle
  #     DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
  #   volumes:
  #     - .:/myapp
  #     - bundle_data:/myapp/vendor/bundle
  #   depends_on:
  #     - db
  #     - redis

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec sidekiq"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      RAILS_ENV: development
      BUNDLE_PATH: /myapp/vendor/bundle
      GEM_HOME: /usr/local/bundle
    volumes:
      - .:/myapp
      - bundle_data:/myapp/vendor/bundle
    depends_on:
      - db
      - redis
      - web

  selenium_chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"

volumes:
  postgres_volume:
  bundle_data:
  redis_data:
