version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      PORT: 8080
    ports:
      - "8080:8080"
    restart: always