version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "/rails/bin/docker-entrypoint"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: